name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    continue-on-error: ${{ matrix.experimental }}

    strategy:
      fail-fast: true
      matrix:
        experimental: [false]
        ruby:
          - 2.2.10
          - 2.3.8
          - 2.4.9
          - 2.5.8
          - 2.6.6
          - 2.7.2
          - ruby-head
          - truffleruby-head
        gemfile:
          # These are located in the gemfiles/ folder
          - rails42
          - rails50
          - rails51
          - rails52
          - rails60
          - rails42_haml
          - rails50_haml
          - rails51_haml
          - rails52_haml
          - rails60_haml
          - rails42_boc
          - rails50_boc
          - rails51_boc
          - rails52_boc
          - rails60_boc
          - rack
          - rack_boc
          - pry09
        exclude:
          - { ruby: 2.2.10,           gemfile: rails60,            experimental: false }
          - { ruby: 2.2.10,           gemfile: rails60_boc,        experimental: false }
          - { ruby: 2.2.10,           gemfile: rails60_haml,       experimental: false }
          - { ruby: 2.3.8,            gemfile: rails42,            experimental: false }
          - { ruby: 2.3.8,            gemfile: rails42_boc,        experimental: false }
          - { ruby: 2.3.8,            gemfile: rails42_haml,       experimental: false }
          - { ruby: 2.3.8,            gemfile: rails60,            experimental: false }
          - { ruby: 2.3.8,            gemfile: rails60_boc,        experimental: false }
          - { ruby: 2.3.8,            gemfile: rails60_haml,       experimental: false }
          - { ruby: 2.4.9,            gemfile: rails42,            experimental: false }
          - { ruby: 2.4.9,            gemfile: rails42_boc,        experimental: false }
          - { ruby: 2.4.9,            gemfile: rails42_haml,       experimental: false }
          - { ruby: 2.4.9,            gemfile: rails60,            experimental: false }
          - { ruby: 2.4.9,            gemfile: rails60_boc,        experimental: false }
          - { ruby: 2.4.9,            gemfile: rails60_haml,       experimental: false }
          - { ruby: 2.5.8,            gemfile: rails42,            experimental: false }
          - { ruby: 2.5.8,            gemfile: rails42_boc,        experimental: false }
          - { ruby: 2.5.8,            gemfile: rails42_haml,       experimental: false }
          - { ruby: 2.6.6,            gemfile: rails42,            experimental: false }
          - { ruby: 2.6.6,            gemfile: rails42_boc,        experimental: false }
          - { ruby: 2.6.6,            gemfile: rails42_haml,       experimental: false }
          - { ruby: 2.7.2,            gemfile: rails42,            experimental: false }
          - { ruby: 2.7.2,            gemfile: rails42_boc,        experimental: false }
          - { ruby: 2.7.2,            gemfile: rails42_haml,       experimental: false }
          - { ruby: ruby-head,        gemfile: rails42,            experimental: false }
          - { ruby: ruby-head,        gemfile: rails42_boc,        experimental: false }
          - { ruby: ruby-head,        gemfile: rails42_haml,       experimental: false }
          - { ruby: truffleruby-head, gemfile: rails42_boc,        experimental: false }
          - { ruby: truffleruby-head, gemfile: rails50_boc,        experimental: false }
          - { ruby: truffleruby-head, gemfile: rails51_boc,        experimental: false }
          - { ruby: truffleruby-head, gemfile: rails52_boc,        experimental: false }
          - { ruby: truffleruby-head, gemfile: rails60_boc,        experimental: false }
          - { ruby: truffleruby-head, gemfile: rack_boc,           experimental: false }
        include:
          - { ruby: 2.2.10,           gemfile: pry010,             experimental: true }
          - { ruby: 2.3.8,            gemfile: pry010,             experimental: true }
          - { ruby: 2.4.9,            gemfile: pry010,             experimental: true }
          - { ruby: 2.5.8,            gemfile: pry010,             experimental: true }
          - { ruby: 2.6.6,            gemfile: pry010,             experimental: true }
          - { ruby: 2.7.2,            gemfile: pry010,             experimental: true }
          - { ruby: ruby-head,        gemfile: pry010,             experimental: true }
          - { ruby: truffleruby-head, gemfile: pry010,             experimental: true }
          - { ruby: 2.2.10,           gemfile: pry011,             experimental: true }
          - { ruby: 2.3.8,            gemfile: pry011,             experimental: true }
          - { ruby: 2.4.9,            gemfile: pry011,             experimental: true }
          - { ruby: 2.5.8,            gemfile: pry011,             experimental: true }
          - { ruby: 2.6.6,            gemfile: pry011,             experimental: true }
          - { ruby: 2.7.2,            gemfile: pry011,             experimental: true }
          - { ruby: ruby-head,        gemfile: pry011,             experimental: true }
          - { ruby: truffleruby-head, gemfile: pry011,             experimental: true }

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-ruby-${{ matrix.ruby }}-gemfile-${{ matrix.gemfile }}-${{ hashFiles('gemfiles/*.gemfile') }}
        restore-keys: |
          ${{ runner.os }}-ruby-${{ matrix.ruby }}-gemfile-${{ matrix.gemfile }}
          ${{ runner.os }}-ruby-${{ matrix.ruby }}

    - name: Configure bundler
      run: bundle config path vendor/bundle

    - name: Bundle install
      run: bundle install --jobs 4 --retry 3
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

    - name: RSpec
      run: bundle exec rspec -f doc --color
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
