name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 2.2.10
          - 2.3.8
          - 2.4.9
          - 2.5.7
          - 2.6.5
          - 2.7.0
          - ruby-head
          - truffleruby-head
        gemfile:
          - gemfiles/rails42.gemfile
          - gemfiles/rails50.gemfile
          - gemfiles/rails51.gemfile
          - gemfiles/rails52.gemfile
          - gemfiles/rails60.gemfile
          - gemfiles/rails42_haml.gemfile
          - gemfiles/rails50_haml.gemfile
          - gemfiles/rails51_haml.gemfile
          - gemfiles/rails52_haml.gemfile
          - gemfiles/rails60_haml.gemfile
          - gemfiles/rails42_boc.gemfile
          - gemfiles/rails50_boc.gemfile
          - gemfiles/rails51_boc.gemfile
          - gemfiles/rails52_boc.gemfile
          - gemfiles/rails60_boc.gemfile
          - gemfiles/rack.gemfile
          - gemfiles/rack_boc.gemfile
          - gemfiles/pry09.gemfile
          - gemfiles/pry010.gemfile
          - gemfiles/pry011.gemfile

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-ruby-${{ matrix.ruby }}-gemfile-${{ matrix.gemfile }}-${{ hashFiles('gemfiles/*.gemfile') }}
        restore-keys: |
          ${{ runner.os }}-ruby-${{ matrix.ruby }}-gemfile-${{ matrix.gemfile }}
          ${{ runner.os }}-ruby-${{ matrix.ruby }}

    - name: Configure bundler
      run: bundle config path vendor/bundle

    - name: Bundle install
      run: bundle install --jobs 4 --retry 3
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    - name: RSpec
      run: bundle exec rspec -f doc --color
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
